#!/usr/bin/env python3
"""generate_grid_configs.py — Generate 400 YAML configs for MoE scaling law Phase 1.

Grid axes:
  d_model ∈ {64, 128, 192, 256}
  D       ∈ {500K, 1M, 2M, 4M}
  G       ∈ {1, 2, 4, 8, 16}       (granularity: n_experts = 8G, d_expert = 4d/G)
  j       ∈ {1, 2, 3, 4, 8}        (top_k = j*G, A = j/8)

Usage:
    python generate_grid_configs.py
"""

import csv
import json
import math
from pathlib import Path

# ── LR scaling law ─────────────────────────────────────────────────────────────

LR_PARAMS_PATH = "results/lr_params.json"
try:
    with open(LR_PARAMS_PATH) as f:
        _p = json.load(f)
    A_ETA    = float(_p["A_eta"])
    BETA_ETA = float(_p["beta_eta"])
    print(f"Loaded LR params from {LR_PARAMS_PATH}: A_eta={A_ETA}, beta_eta={BETA_ETA}")
except FileNotFoundError:
    print(f"WARNING: {LR_PARAMS_PATH} not found — using fallback A_eta=0.5, beta_eta=0.12")
    A_ETA    = 0.5
    BETA_ETA = 0.12

# ── Fixed architecture ──────────────────────────────────────────────────────────

N_LAYERS       = 10
SEQ_LEN        = 1024
VOCAB_SIZE     = 50280
EMBEDDING_SIZE = 50304
BATCH_TOKENS   = 8192  # 8 seqs × 1024

# ── Grid axes ──────────────────────────────────────────────────────────────────

D_MODELS = [
    (8,   1),
    (16,  1),
    (32,  1),
    (64,  1),
    (128, 2),
    (192, 3),
    (256, 4),
]

# device_train_microbatch_size per d_model
# d=8: full batch (8 seqs) fits in one pass
# d=64/128: 4 seqs per microstep (2 grad-accum steps)
# others: keep 1 (conservative for large models on P100)
MICROBATCH = {8: 8, 16: 1, 32: 1, 64: 4, 128: 4, 192: 1, 256: 1}

TOKEN_CONFIGS = [
    ("T0_5M", 500_000),
    ("T1M",   1_000_000),
    ("T2M",   2_000_000),
    ("T4M",   4_000_000),
    ("T8M",   8_000_000),
    ("T16M",  16_000_000),
]

# Long runs — one large D per d_model targeting ≥ 10^15 FLOPs at MFU=0.006 (~4.6 h/run)
# C_min/D (G=1, j=1):  d8→3.46e6,  d16→7.05e6,  d32→1.46e7
# D needed for 10^15:  d8→289M,    d16→142M,     d32→69M
LONG_TOKEN_CONFIG = {
    8:  ("T300M", 300_000_000),
    16: ("T150M", 150_000_000),
    32: ("T75M",   75_000_000),
}
LONG_G_EXCLUDE = {8: {16}}   # G=16 → d_expert=2 for d8, skip

G_VALUES = [1, 2, 4, 8, 16]
J_VALUES = [1, 2, 3, 4, 8]    # top_k = j*G, A = j/8


# ── FLOPs computation ──────────────────────────────────────────────────────────

def compute_C(d_model, n_experts, top_k, d_expert, D):
    """Total training FLOPs — exact per-token formula × D tokens × 3 (fwd+bwd)."""
    c_attn   = 8 * d_model**2 + 4 * SEQ_LEN * d_model
    c_ffn    = 6 * top_k * d_model * d_expert
    c_router = 2 * d_model * n_experts
    m_fwd    = N_LAYERS * (c_attn + c_ffn + c_router) + 2 * d_model * VOCAB_SIZE
    return 3 * m_fwd * D


def compute_N_act(d_model, j):
    """Active parameters per token (independent of G).
    N_act_per_layer = 4d² (attn) + 12·j·d² (FFN active, G cancels)
    """
    return (4 + 12 * j) * d_model**2 * N_LAYERS


def compute_N_tot(d_model, n_experts, d_expert):
    """Total parameters (embedding counted once; weight_tying=True)."""
    n_attn   = 4 * N_LAYERS * d_model**2          # Q, K, V, O per layer
    n_ffn    = N_LAYERS * n_experts * 3 * d_model * d_expert  # SwiGLU: 3 mats
    n_router = N_LAYERS * d_model * n_experts
    n_embed  = EMBEDDING_SIZE * d_model            # shared embed + head
    return n_attn + n_ffn + n_router + n_embed


# ── YAML template ──────────────────────────────────────────────────────────────

YAML_TEMPLATE = """\
# Auto-generated by generate_grid_configs.py — do not edit by hand.
# d_model={d_model}  G={G}  j={j}  A={A:.1%}  D={D_label}  steps={steps}
# n_experts={n_experts}  top_k={top_k}  d_expert={d_expert}
# N_act={N_act:.3e}  N_tot={N_tot:.3e}  C={C:.3e}  lr={lr:.4e}

run_name: {run_name}
seed: 42
dry_run: false
no_pre_train_checkpoint: true
load_path: null

wandb:
  name: {run_name}
  project: olmoe-1
  entity: iliass-lasri-team
  group: grid_phase2_lb

model:
  d_model: {d_model}
  n_heads: {n_heads}
  n_layers: {N_LAYERS}
  mlp_ratio: 4
  mlp_hidden_size: {d_expert}
  weight_tying: true
  alibi: false
  rope: true
  flash_attention: true
  attention_dropout: 0.0
  attention_layer_norm: true
  include_bias: false
  block_type: moe
  layer_norm_type: rms
  layer_norm_with_affine: true
  bias_for_layer_norm: false
  attention_layer_norm_with_affine: true
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: {SEQ_LEN}
  vocab_size: {VOCAB_SIZE}
  embedding_size: {EMBEDDING_SIZE}
  eos_token_id: 0
  pad_token_id: 1
  init_device: meta
  init_fn: normal
  init_std: 0.02
  init_cutoff_factor: 3
  moe_top_k: {top_k}
  moe_num_experts: {n_experts}
  moe_dropless: false
  moe_mlp_impl: dense
  moe_lbl_in_fp32: true
  moe_zloss_weight: 0.001
  moe_loss_weight: 0.001
  moe_routing_type: learned
  moe_gate_type: softmax
  moe_log_expert_assignment: false

compile: null

optimizer:
  name: adamw
  learning_rate: {lr:.6e}
  eps: 1.0e-8
  weight_decay: 0.1
  decay_norm_and_bias: true
  decay_embeddings: true
  betas:
    - 0.9
    - 0.95
  metrics_log_interval: 10

scheduler:
  name: cosine_with_warmup
  units: steps
  t_warmup: {warmup}
  t_max: {steps}
  alpha_f: 0.1

tokenizer:
  identifier: tokenizers/allenai_gpt-neox-olmo-dolma-v1_5.json
  truncate_direction: right

save_folder: /tmp/olmoe_ckpt/{run_name}
remote_save_folder: null
save_overwrite: true
save_interval: 999999
save_interval_ephemeral: null
save_num_checkpoints_to_keep: 0
sharded_checkpointer: olmo_core
save_interval_unsharded: null
save_num_unsharded_checkpoints_to_keep: 0

max_duration: {steps}
time_limit: null
extra_steps_after_cancel: 0
global_train_batch_size: 8
device_train_microbatch_size: {microbatch_size}

precision: fp32
distributed_strategy: fsdp

fsdp:
  wrapping_strategy: by_block
  precision: mixed
  sharding_strategy: FULL_SHARD

max_grad_norm: 1.0
max_grad_norm_ratio: null

speed_monitor:
  window_size: 1

data:
  pad_direction: right
  num_workers: 0
  drop_last: true
  pin_memory: true
  prefetch_factor: null
  persistent_workers: false
  timeout: 0
  instance_filter:
    repetition_max_period: 13
    repetition_min_period: 1
    repetition_max_count: 32
  paths:
    - data/tokenized/wiki-0000.npy/part-0-00000.npy
    - data/tokenized/wiki/part-0-00001.npy
    - data/tokenized/pes2o/pes2o-0000.npy

eval_interval: 999999
eval_subset_num_batches: 0
device_eval_batch_size: 1
evaluators: []
"""


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    out_dir = Path("configs/grid")
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest_rows = []
    total_gpu_hours = 0.0

    # Rough FLOPs/s on P100 fp32: ~10 TFLOP/s = 1e13 FLOPs/s
    P100_FP32_FLOPS = 10e12

    for d_model, n_heads in D_MODELS:
        microbatch_size = MICROBATCH[d_model]
        for D_label, D in TOKEN_CONFIGS:
            for G in G_VALUES:
                n_experts = 8 * G
                d_expert  = (4 * d_model) // G
                for j in J_VALUES:
                    top_k  = j * G
                    A      = j / 8

                    steps  = D // BATCH_TOKENS
                    warmup = max(10, math.ceil(0.01 * steps))

                    C  = compute_C(d_model, n_experts, top_k, d_expert, D)
                    lr = A_ETA * C ** (-BETA_ETA)

                    N_act = compute_N_act(d_model, j)
                    N_tot = compute_N_tot(d_model, n_experts, d_expert)

                    # Filename: d{DIM:03d}_G{G:02d}_A{j}_{TLABEL}.yml
                    run_name = f"d{d_model:03d}_G{G:02d}_A{j}_{D_label}"
                    yaml_path = out_dir / f"{run_name}.yml"

                    yaml_content = YAML_TEMPLATE.format(
                        run_name=run_name,
                        d_model=d_model,
                        n_heads=n_heads,
                        N_LAYERS=N_LAYERS,
                        SEQ_LEN=SEQ_LEN,
                        VOCAB_SIZE=VOCAB_SIZE,
                        EMBEDDING_SIZE=EMBEDDING_SIZE,
                        G=G,
                        j=j,
                        A=A,
                        D_label=D_label,
                        n_experts=n_experts,
                        top_k=top_k,
                        d_expert=d_expert,
                        steps=steps,
                        warmup=warmup,
                        C=C,
                        lr=lr,
                        N_act=N_act,
                        N_tot=N_tot,
                        microbatch_size=microbatch_size,
                    )
                    yaml_path.write_text(yaml_content)

                    gpu_hours = (C / P100_FP32_FLOPS) / 3600
                    total_gpu_hours += gpu_hours

                    manifest_rows.append(dict(
                        run_name=run_name,
                        d_model=d_model,
                        n_layers=N_LAYERS,
                        G=G,
                        j=j,
                        A=A,
                        top_k=top_k,
                        n_experts=n_experts,
                        d_expert=d_expert,
                        N_act=N_act,
                        N_tot=N_tot,
                        D=D,
                        steps=steps,
                        warmup=warmup,
                        C=C,
                        lr=lr,
                    ))

    # Write manifest
    manifest_path = out_dir / "manifest.csv"
    fields = ["run_name", "d_model", "n_layers", "G", "j", "A",
              "top_k", "n_experts", "d_expert", "N_act", "N_tot",
              "D", "steps", "warmup", "C", "lr"]
    with open(manifest_path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(manifest_rows)
    print(f"Wrote {manifest_path}  ({len(manifest_rows)} rows)")

    # Print summary table
    print(f"\n{'run_name':<30} {'d':>4} {'G':>4} {'j':>3} {'A':>6} "
          f"{'top_k':>6} {'n_exp':>6} {'d_exp':>6} "
          f"{'N_act':>10} {'C':>12} {'lr':>10}")
    print("-" * 100)
    for r in manifest_rows:
        print(f"{r['run_name']:<30} {r['d_model']:>4} {r['G']:>4} {r['j']:>3} "
              f"{r['A']:>6.1%} {r['top_k']:>6} {r['n_experts']:>6} "
              f"{r['d_expert']:>6} {r['N_act']:>10.3e} {r['C']:>12.3e} "
              f"{r['lr']:>10.4e}")

    print(f"\nTotal configs: {len(manifest_rows)}")
    print(f"Total estimated GPU-hours (P100 fp32 @10 TFLOP/s peak): {total_gpu_hours:.1f} h")
    print(f"  NOTE: actual throughput at bs=2 is ~10x below peak (memory-bandwidth bound)")
    print(f"  Realistic estimate: ~{total_gpu_hours*10:.0f} GPU-hours, "
          f"~{total_gpu_hours*10/3:.0f} h wall-clock on 3 GPUs")

    # ── Long runs: d8/d16/d32 configs targeting ≥ 10^15 FLOPs ───────────────────
    long_rows = []
    for d_model, n_heads in D_MODELS:
        if d_model not in LONG_TOKEN_CONFIG:
            continue
        D_label, D = LONG_TOKEN_CONFIG[d_model]
        excluded_g = LONG_G_EXCLUDE.get(d_model, set())
        microbatch_size = MICROBATCH[d_model]
        steps  = D // BATCH_TOKENS
        warmup = max(10, math.ceil(0.01 * steps))

        for G in G_VALUES:
            if G in excluded_g:
                continue
            n_experts = 8 * G
            d_expert  = (4 * d_model) // G
            for j in J_VALUES:
                top_k = j * G
                A     = j / 8
                C     = compute_C(d_model, n_experts, top_k, d_expert, D)
                lr    = A_ETA * C ** (-BETA_ETA)
                N_act = compute_N_act(d_model, j)
                N_tot = compute_N_tot(d_model, n_experts, d_expert)

                run_name  = f"d{d_model:03d}_G{G:02d}_A{j}_{D_label}"
                yaml_path = out_dir / f"{run_name}.yml"
                yaml_path.write_text(YAML_TEMPLATE.format(
                    run_name=run_name, d_model=d_model, n_heads=n_heads,
                    N_LAYERS=N_LAYERS, SEQ_LEN=SEQ_LEN, VOCAB_SIZE=VOCAB_SIZE,
                    EMBEDDING_SIZE=EMBEDDING_SIZE, G=G, j=j, A=A,
                    D_label=D_label, n_experts=n_experts, top_k=top_k,
                    d_expert=d_expert, steps=steps, warmup=warmup, C=C,
                    lr=lr, N_act=N_act, N_tot=N_tot,
                    microbatch_size=microbatch_size,
                ))
                long_rows.append(dict(
                    run_name=run_name, d_model=d_model, G=G, j=j, A=A,
                    D=D, steps=steps, C=C,
                ))

    print(f"\nLong-run configs written: {len(long_rows)}")
    for d_model in sorted({r['d_model'] for r in long_rows}):
        subset = [r for r in long_rows if r['d_model'] == d_model]
        label, D = LONG_TOKEN_CONFIG[d_model]
        cmin = min(r['C'] for r in subset)
        cmax = max(r['C'] for r in subset)
        t_h  = cmin / (0.006 * 10e12) / 3600
        print(f"  d{d_model:3d}  {label}  {len(subset):2d} configs  "
              f"C=[{cmin:.2e},{cmax:.2e}]  ~{t_h:.1f}h/run @MFU=0.006")


if __name__ == "__main__":
    main()
